spring.jpa.properties.hibernate.format_sql=true

spring.datasource.url=${SMARTPARKING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/smartparking}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${SMARTPARKING_DATASOURCE_USERNAME:smartparking}
spring.datasource.password=${SMARTPARKING_DATASOURCE_PASSWORD:smartparking}
spring.jpa.hibernate.ddl-auto=update

smartparking.yolo.base-url=${SMARTPARKING_YOLO_BASE_URL:http://fastapi:8000}
smartparking.jwt.secret=${SMARTPARKING_JWT_SECRET:smartparking-docker-secret-smartparking-docker-secret}
smartparking.ollama.base-url=${SMARTPARKING_OLLAMA_BASE_URL:http://ollama:11434}
smartparking.ollama.model=${SMARTPARKING_OLLAMA_MODEL:qwen2.5:1.5b}
smartparking.storage.type=${SMARTPARKING_STORAGE_TYPE:minio}
smartparking.storage.endpoint=${SMARTPARKING_STORAGE_ENDPOINT:http://minio:9000}
smartparking.storage.bucket=${SMARTPARKING_STORAGE_BUCKET:smartparking-minio-assets}
smartparking.storage.access-key=${SMARTPARKING_STORAGE_ACCESS_KEY:minioadmin}
smartparking.storage.secret-key=${SMARTPARKING_STORAGE_SECRET_KEY:minioadmin}

server.address=0.0.0.0
smartparking.naver-map.client-id=${SMARTPARKING_NAVER_MAP_CLIENT_ID:}
smartparking.naver-search.client-id=${SMARTPARKING_NAVER_SEARCH_CLIENT_ID:}
smartparking.naver-search.client-secret=${SMARTPARKING_NAVER_SEARCH_CLIENT_SECRET:}
smartparking.gemini.api-key=${SMARTPARKING_GEMINI_API_KEY:}
smartparking.jwt.expiration-ms=${SMARTPARKING_JWT_EXPIRATION_MS:3600000}
spring.servlet.multipart.max-file-size=2GB
spring.servlet.multipart.max-request-size=2GB
